# Generated by Django 4.1 on 2023-05-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='value',
            field=models.CharField(max_length=30),
        ),
    ]
